obj-$(CONFIG_TEGRA_CAMERA_PLATFORM) += camera/
CONFIG_TEGRA_GRHOST := y
obj-$(CONFIG_TEGRA_GRHOST) += host/
CONFIG_TEGRA_GRHOST := n
obj-$(CONFIG_ARCH_TEGRA) += nvmap/

obj-$(CONFIG_TEGRA_GR_VIRTUALIZATION) += virt/

GCOV_PROFILE := y
#subdir-ccflags-y := -Werror

obj-$(CONFIG_TEGRA_DC) += dc/
obj-$(CONFIG_FB_TEGRA) += fb.o
