# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_RAS)	+= ras.o
obj-$(CONFIG_DEBUG_FS)	+= debugfs.o
obj-$(CONFIG_RAS_CEC)	+= cec.o

ifdef CONFIG_ARCH_TEGRA_19x_SOC

obj-$(CONFIG_ARM64_RAS) += arm64_ras.o

endif

