# SPDX-License-Identifier: GPL-2.0
#
# Makefile for PCI Endpoint Support
#

obj-$(CONFIG_PCI_ENDPOINT_CONFIGFS)	+= pci-ep-cfs.o
obj-$(CONFIG_PCI_ENDPOINT)		+= pci-epc-core.o pci-epf-core.o\
					   pci-epc-mem.o functions/
obj-$(CONFIG_PCIE_EPF_NV_TEST)		+= pci-epf-nv-test.o
obj-$(CONFIG_PCIE_EPF_TEGRA_VNET)	+= pci-epf-tegra-vnet.o
