# SPDX-License-Identifier: GPL-2.0
#
# Makefile for metering ic drivers
#

obj-$(CONFIG_ADE7854) += ade7854.o
obj-$(CONFIG_ADE7854_I2C) += ade7854-i2c.o
obj-$(CONFIG_ADE7854_SPI) += ade7854-spi.o
obj-$(CONFIG_INA219) += ina219.o
obj-$(CONFIG_INA230) += ina230.o
obj-$(CONFIG_INA3221) += ina3221.o
