ifdef CONFIG_ARCH_TEGRA_19x_SOC

GCOV_PROFILE := y
ccflags-y += -I$(srctree)/drivers/video/tegra/camera
ccflags-y += -I$(srctree)/drivers/media/platform/tegra
ccflags-y += -I$(srctree)/drivers/video/tegra/host
ccflags-y += -I$(srctree)/include
ccflags-y += -Werror

obj-y += csi5_fops.o

endif
