# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_RESET_TEGRA_BPMP)		+= reset-bpmp.o
obj-$(CONFIG_ARCH_TEGRA_18x_SOC)        += reset-nv-bpmp.o
obj-$(CONFIG_ARCH_TEGRA_18x_SOC)        += reset-tegra.o

